package logging;

public enum LogKeys {
    TIMESTAMP,
    GOOD_ID,
    TRADE_OFFER,
    TRADE_RESULT,
    AGENT_NAME,
    PRICE_PER_ITEM,
    PROBABILITY,
    QUANTITY_DESIRED,
    QUANTITY_OFFERED,
    QUANTITY_TRADED,
    CREATOR,
    ITEM_VALUES,
    INVENTORY,
}
